### ISSUE TITLE
Add checkFiles function

### ISSUE THREAD

**Issue by michaelmcd18** [metrumresearchgroup/review#125]
Allow user to input multiple scripts, return the latest revision and author to those scripts. Also include if the file has been QCed and who the QCer was

**Comment by andersone1** [comment]
`review::fileSummary()`

- All Authors
- Latest Author
- Latest Revision Date (Days ago)
- Ever been QCed?
- Is the QC up to date?

`purrr::map(list.files(.dir), ~ review::fileSummary(.x))`
