### ISSUE TITLE
clock-dependent dirSummary test failure

### ISSUE THREAD

**Issue by kyleam** [metrumresearchgroup/review#58]
Depending on the local time zone and current time, the below test failure can be triggered:

```
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure ('test-dirSummary.R:37:3'): dirSummary captures the expected QC status of all scripts ──
  as.Date(dirSummaryRes$data$`Latest edit`[1]) (`actual`) not equal to Sys.Date() (`expected`).

  `actual`:   "2023-12-05"
  `expected`: "2023-12-04"
```

 * `svn info --xml` returns the date in UTC (e.g., "2023-12-05T14:04:27.050339Z"), and `svnInfo()` [parses][1] that to a `POSIXct` object.  (There's some other processing that goes on downstream, but this is the only processing that matters.)

 * a [test][2] in `test-dirSummary.R` converts that value with `as.Date()` and expects it to be equal to `Sys.Date()`

That expectation is invalid because `Sys.Date()` is the current day for the current time zone.

One fix would be to replace the `Sys.Date()` value with a date for UTC (say `format(Sys.time(), "%Y-%m-%d", tz = "UTC")`).  However, that would leave a harder-to-hit failure: if the test is executed right at the boundary of a day change, with the `svnInfo` call before and the `Sys.time()` call for the assertion after, the results would not match.

Instead you could avoid converting to a date.  Subtract the `POSIXct` value in `dirSummaryRes` from `Sys.time()`, and assert that the time difference is under `N` seconds.  `N` should be large enough that, if it were to be reached, it'd be an indication that something was going very wrong with the test run (say 120 seconds in this case?).

[1]: https://github.com/metrumresearchgroup/review/blob/193edfdaa6762d520f699df7b502c0bd96029c25/R/svnInfo.R#L24
[2]: https://github.com/metrumresearchgroup/review/blob/193edfdaa6762d520f699df7b502c0bd96029c25/tests/testthat/test-dirSummary.R#L37

cc: @andersone1 @michaelmcd18

**Comment by andersone1** [comment]
@kyleam is this blocking this version of review from getting into the next mpn? (I e how urgent is this)

**Comment by kyleam** [comment]
> is this blocking this version of review from getting into the next mpn? 

No.

**Comment by andersone1** [comment]
> > is this blocking this version of review from getting into the next mpn? 
> 
> 
> 
> No.

@kyleam Ok, that's good to know, thanks for bringing this to our attention.

@michaelmcd18 i can review the PR for this issue whenever it's ready

**Comment by michaelmcd18** [comment]
Great idea @kyleam, we'll implement this:
`Instead you could avoid converting to a date. Subtract the POSIXct value in dirSummaryRes from Sys.time(), and assert that the time difference is under N seconds. N should be large enough that, if it were to be reached, it'd be an indication that something was going very wrong with the test run (say 120 seconds in this case?).`
