### ISSUE TITLE
renderQCsummary can take a very long time

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/review#79]
This was a repository where we just did sse. It's currently taking quite a long time to generate the summary. I don't know if it's actually going to take 30 min for this to finish, but it's looking about that way. It's possible this is taking a long time because we need to go get the files from S3 (warmup effect) but thinking this could just be lots of files. 

<img width="728" alt="Screenshot 2024-04-01 at 08 42 14" src="https://github.com/metrumresearchgroup/review/assets/16908301/26dc0806-5bc7-4cad-99a8-fed609434c34">

**Comment by andersone1** [comment]
@kylebaron which version of review are you using?

**Comment by kylebaron** [comment]
@andersone1 
```r
> packageVersion("review")
[1] ‘3.7.0’
```

**Comment by kylebaron** [comment]
There was 816 pages in the rendered report.

**Comment by andersone1** [comment]
@kylebaron Wow, OK.

3.7.0 is the newest version that runs faster that the prior versions.

Would it have helped if a specific directory could have been pointed to rather than the whole project? (e.g. `/script`)

**Comment by kylebaron** [comment]
@andersone1  - yeah, either that way or some directories to ignore.

**Comment by kylebaron** [comment]
@andersone1  - it's `dirSummary()`, not knitting the pdf.

**Comment by andersone1** [comment]
@kylebaron The functions `dirSummary` and `renderQCSummary` will have a `.dirs_exclude` option in the upcoming release.

We will also print each directory / the number of files, so the user can see which dirs they may want to exclude, e.g.:

<img width="237" alt="image" src="https://github.com/metrumresearchgroup/review/assets/28537780/4c317565-e8f1-42a5-b4fb-e840a3d92c00">

**Comment by kylebaron** [comment]
@andersone1  - did you ever look at `svn list -v` on a directory to get the last revision?

**Comment by andersone1** [comment]
@kylebaron

I have not tried `svn list -v`, but I will look into that (we currently use `svn info`).

Also, as FYI, we have just released a new version of the package (`3.8.1`), with two updates to `renderQCsummary`:

#### **1.** The files that will be added to the report are printed to the console (so the user has an idea how many there are), which looks like this:

<img width="258" alt="image" src="https://github.com/metrumresearchgroup/review/assets/28537780/42fda949-0e58-46b0-9043-f64b9853f463">

#### **2.** The user can now specify directories to exclude
For example, in the above case, the user could exclude `script/e-appendix` from the report with `renderQCsummary(.dirs_exclude = c("script/e-appendix"))`

This version of `review` is available here:
`- review: https://s3.amazonaws.com/mpn.metworx.dev/releases/review/3.8.1`

**Comment by andersone1** [comment]
`review:::svnCommand("list", .flags = "--depth infinity")`

**Comment by andersone1** [comment]
@kylebaron 

svn list implemented [here](https://github.com/metrumresearchgroup/review/pull/98) (runs much faster now).
