### ISSUE TITLE
renderQCsummary returns blank document when it is not run from root

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/review#81]
When I run from `script`, the document is blank (see attached); when I move back up to  the project root, the document is filled in. 

```r
> getwd()
[1] "/path/to/project/script"
> review::renderQCSummary()
                                                                
> review::renderQCSummary()
                                                                
> setwd("../")
> review::renderQCSummary()

```

[qc-summary-blank.pdf](https://github.com/metrumresearchgroup/review/files/14837183/qc-summary-blank.pdf)

**Comment by andersone1** [comment]
@kylebaron Thank you for drawing this to our attention. This will be fixed in the upcoming release.
